import { IoCheckmarkCircle, IoTicketOutline } from "react-icons/io5";
import {
  MdOutlinePersonalInjury,
  MdOutlineDashboard,
  MdOutlineShowChart,
  MdOutlineInventory2,
} from "react-icons/md";
import { FaSearchPlus, FaClinicMedical } from "react-icons/fa";
import { TbReport } from "react-icons/tb";
import { UserRoundPlus, CalendarPlus2, Podcast, LineChart } from "lucide-react";

// HOMEPAGE DATA
export const NAV_ITEMS = [
  {
    name: "Home",
    url: "/",
  },
  {
    name: "About Us",
    url: "/#about-us",
  },
  {
    name: "Services",
    url: "/#services",
  },
  {
    name: "Contact Us",
    url: "/contact-us",
  },
];

export const MEDCONNECT_OFFERS = [
  {
    icon: "/assets/icons/access-24-7.svg",
    name: "24/7 Access",
    description:
      "Enables patients to access healthcare services around the clock, breaking the barriers of limited operational hours of physical CHPS compounds.",
  },
  {
    icon: "/assets/icons/improved-health.svg",
    name: "Improved Health",
    description:
      "Quick access to medical advice and early interventions can prevent the worsening of conditions.",
  },
  {
    icon: "/assets/icons/health-policy.svg",
    name: "Health Policy",
    description:
      "Offers educational materials and resources to improve health literacy among rural populations.",
  },
  {
    icon: "/assets/icons/empowerment.svg",
    name: "Empowerment",
    description:
      "Equips community health workers with mobile tools to collect data, track patient progress, and deliver care more effectively.",
  },
];

export const MEDCONNECT_SERVICES = [
  {
    name: "Community Health Outreach",
    image: "/assets/images/community-outreach.jpg",
    description:
      "We conduct regular community health outreach programs to educate and inform residents about preventive healthcare, maternal and child health, nutrition, and sanitation. These initiatives help raise awareness and promote healthier lifestyles within the community.",
  },
  {
    name: "On-Demand Medical Assistance",
    image: "/assets/images/medical-assistance.jpg",
    description:
      "Our application allows community health workers to provide immediate medical assistance and support for emergencies and chronic conditions. With access to up-to-date patient records and resources, they can deliver timely and effective care.",
  },
  {
    name: "Routine Health Monitoring",
    image: "/assets/images/health-monitoring.jpg",
    description:
      "Through our platform, we facilitate regular health check-ups and monitoring for patients with chronic illnesses, pregnant women, and infants. This ensures early detection of potential health issues and consistent follow-up care, improving overall health outcomes in rural areas.",
  },
];

export const MEDCONNECT_OBJECTIVES = [
  {
    name: "Enhance Healthcare Access",
    icon: "/assets/icons/enhance-healthcare.svg",
  },
  {
    name: "Promote Preventive Healthcare",
    icon: "/assets/icons/promote-healthcare.svg",
  },
  {
    name: "Support Community Health Workers",
    icon: "/assets/icons/community-support.svg",
  },
];

export const MEDCONNECT_OBJECTIVES_CHECKS = [
  {
    name: "Compassion",
    icon: IoCheckmarkCircle,
  },
  {
    name: "Integrity",
    icon: IoCheckmarkCircle,
  },
  {
    name: "Innovation",
    icon: IoCheckmarkCircle,
  },
  {
    name: "Collaboration",
    icon: IoCheckmarkCircle,
  },
  {
    name: "Accessibility",
    icon: IoCheckmarkCircle,
  },
  {
    name: "Excellence",
    icon: IoCheckmarkCircle,
  },
];

export const MEDCONNECT_FAQS = [
  {
    question: "What is the purpose of this application?",
    answer:
      "This application aims to improve healthcare accessibility for rural communities by connecting them with healthcare providers, facilitating medical services, and offering health education and resources.",
  },
  {
    question: "How do I add connect a CHPS compound to this platform?",
    answer:
      "You can connect a CHPS compound to this platform for free by visiting the application dashboard's Add Compound page.",
  },
  {
    question: "Are the services provided through this application free?",
    answer: "Yes, the application provides free access to medical services.",
  },
  {
    question: "Can I access my medical records through the application?",
    answer:
      "Yes, you can access your medical records through the application. Your medical records will be stored securely.",
  },
  {
    question: "How can I give feedback on the services I received?",
    answer:
      "You can give feedback on the services you received through the application's Feedback Page. Your feedback will be used to improve the quality of the services provided.",
  },
  {
    question: "What languages are supported by the application?",
    answer:
      "The application supports different languages such as English, French, Twi, Ewe, Ga and many more.",
  },
];

export const MEDCONNECT_RECENT_ARTICLES = [
  {
    url: "/",
    title: "The Future of Remote Healthcare",
    description:
      "Telemedicine has seen significant advancements in recent years, driven by the COVID-19 pandemic. This article explores the latest technologies and innovations that are shaping the future of remote healthcare, including AI-driven ...",
    image: "/assets/images/remote-healthcare.jpg",
    author: "Teany Walter",
    publishedDate: "20th April, 2024",
    avatar: "/assets/avatars/avatar-teany.svg",
  },
  {
    url: "/",
    title: "Breakthrough in Cancer Treatment",
    description:
      "Researchers have developed a new cancer therapy that shows great promise in early clinical trials. This therapy, which involves targeted gene editing, has the potential to revolutionize cancer treatment by specifically...",
    image: "/assets/images/cancer-treatment.jpg",
    author: "Terry Bleu",
    publishedDate: "06th June, 2024",
    avatar: "/assets/avatars/avatar-terry.svg",
  },
  {
    url: "/",
    title: "Mental Health Crisis Among Youth",
    description:
      "The mental health crisis among young people is escalating, with rising rates of anxiety, depression, and suicide. This article examines the contributing factors, including social media, academic pressure, and the impact of the ...",
    image: "/assets/images/healthy-foods.jpg",
    author: "Lily Garret",
    publishedDate: "29th Aug, 2024",
    avatar: "/assets/avatars/avatar-lily.svg",
  },
];

export const MEDCONNECT_TESTIMONIALS = [
  {
    testimony:
      "MedConnect has transformed our healthcare experience. Booking appointments and consulting with specialists has never been easier. The convenience and efficiency of the app are unmatched.",
    author: "Jane Doe",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    jobTitle: "Teacher",
  },
  {
    testimony:
      "As a busy professional, finding time for doctor visits was always tough. MedConnect's virtual consultations have been a game-changer, allowing me to get medical advice without interrupting my work schedule.",
    author: "John Smith",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    jobTitle: "Software Engineer",
  },
  {
    testimony:
      "MedConnect has provided my elderly parents with the medical support they need right from home. The app is user-friendly, and the virtual visits have reduced the need for frequent trips to the clinic.",
    author: "Sarah Lee",
    avatar: "https://randomuser.me/api/portraits/women/47.jpg",
    jobTitle: "Marketing Manager",
  },
  {
    testimony:
      "Thanks to MedConnect, managing my chronic condition has become much easier. The app's reminders and easy access to my medical history have made a significant difference in my treatment plan.",
    author: "Mike Johnson",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    jobTitle: "Freelance Writer",
  },
  {
    testimony:
      "Living in a rural area, MedConnect has been a blessing. The ability to consult with top doctors without having to travel has improved our family's access to quality healthcare.",
    author: "Emma Brown",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    jobTitle: "Farmer",
  },
];

// DASHBOARD DATA
export const MEDCONNECT_DASHBOARD_LINKS = [
  { name: "Dashboard", path: "/dashboard", icon: MdOutlineDashboard },
  {
    name: "Patients",
    path: "/dashboard/patients",
    icon: MdOutlinePersonalInjury,
  },
  {
    name: "Appointments",
    path: "/dashboard/appointments",
    icon: CalendarPlus2,
  },
  {
    name: "Inventory",
    path: "/dashboard/inventory",
    icon: MdOutlineInventory2,
  },
  {
    name: "Diagnostic Support",
    path: "/dashboard/diagnostic-support",
    icon: FaSearchPlus,
  },
  {
    name: "Health Officials",
    path: "/dashboard/health-officials",
    icon: UserRoundPlus,
  },
  {
    name: "Disease Analysis",
    path: "/dashboard/disease-analysis",
    icon: MdOutlineShowChart,
  },
  {
    name: "Outreach Programs",
    path: "/dashboard/outreach-programs",
    icon: Podcast,
  },
  {
    name: "Reports",
    path: "/dashboard/reports",
    icon: TbReport,
  },
];

export const MEDCONNECT_SUPER_ADMIN_DASHBOARD_LINKS = [
  { name: "Dashboard", path: "/dashboard", icon: MdOutlineDashboard },
  {
    name: "Compounds",
    path: "/dashboard/compounds",
    icon: FaClinicMedical,
  },
  {
    name: "System Analytics",
    path: "/dashboard/system-analytics",
    icon: LineChart,
  },
  {
    name: "Outreach Programs",
    path: "/dashboard/outreach-programs",
    icon: Podcast,
  },
  {
    name: "Tickets",
    path: "/dashboard/tickets",
    icon: IoTicketOutline,
  },
  {
    name: "Reports",
    path: "/dashboard/reports",
    icon: TbReport,
  },
];

export const MEDCONNECT_DASHBOARD_UPCOMING_APPOINTMENTS = [
  {
    patientName: "David Davis",
    patientID: "PID5683",
    assignedHO: "Dr. Murphy",
    appointmentDate: "2023-05-22",
    appointmentTime: "15:20",
  },
  {
    patientName: "Hank Martinez",
    patientID: "PID1342",
    assignedHO: "Dr. Lee",
    appointmentDate: "2023-09-14",
    appointmentTime: "14:50",
  },
  {
    patientName: "Alice Brown",
    patientID: "PID2487",
    assignedHO: "Dr. Johnson",
    appointmentDate: "2023-11-03",
    appointmentTime: "10:30",
  },
  {
    patientName: "Eve Johnson",
    patientID: "PID0783",
    assignedHO: "Dr. Smith",
    appointmentDate: "2023-03-12",
    appointmentTime: "13:10",
  },
  {
    patientName: "Grace Lee",
    patientID: "PID6854",
    assignedHO: "Dr. Patel",
    appointmentDate: "2023-02-18",
    appointmentTime: "12:40",
  },
  {
    patientName: "Carol Garcia",
    patientID: "PID2197",
    assignedHO: "Dr. Smith",
    appointmentDate: "2023-10-30",
    appointmentTime: "09:20",
  },
  {
    patientName: "John Clark",
    patientID: "PID9512",
    assignedHO: "Dr. Johnson",
    appointmentDate: "2023-01-23",
    appointmentTime: "11:00",
  },
  {
    patientName: "Jane Garcia",
    patientID: "PID3771",
    assignedHO: "Dr. Patel",
    appointmentDate: "2023-08-16",
    appointmentTime: "16:30",
  },
  {
    patientName: "Bob Brown",
    patientID: "PID4329",
    assignedHO: "Dr. Lee",
    appointmentDate: "2023-06-11",
    appointmentTime: "11:50",
  },
  {
    patientName: "Carol White",
    patientID: "PID8457",
    assignedHO: "Dr. Murphy",
    appointmentDate: "2023-07-27",
    appointmentTime: "14:20",
  },
  {
    patientName: "Frank Davis",
    patientID: "PID0913",
    assignedHO: "Dr. Patel",
    appointmentDate: "2023-05-09",
    appointmentTime: "12:10",
  },
  {
    patientName: "Alice Martinez",
    patientID: "PID5281",
    assignedHO: "Dr. Johnson",
    appointmentDate: "2023-04-19",
    appointmentTime: "15:40",
  },
  {
    patientName: "John Lee",
    patientID: "PID7884",
    assignedHO: "Dr. Smith",
    appointmentDate: "2023-03-05",
    appointmentTime: "10:10",
  },
  {
    patientName: "Eve Clark",
    patientID: "PID6378",
    assignedHO: "Dr. Murphy",
    appointmentDate: "2023-09-24",
    appointmentTime: "09:50",
  },
  {
    patientName: "Hank Johnson",
    patientID: "PID2843",
    assignedHO: "Dr. Patel",
    appointmentDate: "2023-01-09",
    appointmentTime: "13:50",
  },
  {
    patientName: "Jane White",
    patientID: "PID9842",
    assignedHO: "Dr. Lee",
    appointmentDate: "2023-12-08",
    appointmentTime: "10:00",
  },
  {
    patientName: "Frank Smith",
    patientID: "PID3124",
    assignedHO: "Dr. Murphy",
    appointmentDate: "2023-11-15",
    appointmentTime: "14:40",
  },
  {
    patientName: "David Clark",
    patientID: "PID4703",
    assignedHO: "Dr. Patel",
    appointmentDate: "2023-02-28",
    appointmentTime: "16:00",
  },
  {
    patientName: "Grace Johnson",
    patientID: "PID1298",
    assignedHO: "Dr. Smith",
    appointmentDate: "2023-10-04",
    appointmentTime: "15:10",
  },
  {
    patientName: "Carol Lee",
    patientID: "PID6832",
    assignedHO: "Dr. Johnson",
    appointmentDate: "2023-07-11",
    appointmentTime: "13:20",
  },
];

export const MEDCONNECT_DASHBOARD_REPORTS = [
  {
    title: "Monthly Patient Visits",
    description: "A summary of patient visits in the last month.",
  },
  {
    title: "Medication Inventory",
    description: "Current stock levels of all medications.",
  },
  {
    title: "Financial Summary",
    description:
      "Overview of financial performance including revenue and expenses.",
  },
  {
    title: "Patient Satisfaction Survey",
    description: "Results from the latest patient satisfaction survey.",
  },
  {
    title: "Staff Performance",
    description: "Assessment of staff performance for the past quarter.",
  },
  {
    title: "Annual Health Outcomes",
    description: "Yearly report on patient health outcomes and improvements.",
  },
  {
    title: "Emergency Room Statistics",
    description: "Detailed statistics on ER visits and outcomes.",
  },
  {
    title: "Outpatient Services Utilization",
    description: "Analysis of outpatient services and their usage.",
  },
  {
    title: "Research and Development",
    description: "Summary of ongoing research projects and developments.",
  },
  {
    title: "Community Outreach",
    description: "Report on community outreach programs and their impact.",
  },
];

export const MEDCONNECT_DASHBOARD_RECENT_ACTIVITIES = [
  {
    title: "New Patient Registered",
    description: "John Doe has registered as a new patient.",
    timeAgo: "9 min ago",
  },
  {
    title: "Appointment Scheduled",
    description: "Jane Smith scheduled an appointment with Dr. Johnson.",
    timeAgo: "20 min ago",
  },
  {
    title: "Medication Restocked",
    description: "Paracetamol has been restocked in the pharmacy.",
    timeAgo: "45 min ago",
  },
  {
    title: "Lab Results Available",
    description: "Lab results for patient Alice Brown are now available.",
    timeAgo: "1 hour ago",
  },
  {
    title: "New Staff Member",
    description: "Dr. Emily White has joined the cardiology department.",
    timeAgo: "2 hours ago",
  },
  {
    title: "System Maintenance Completed",
    description:
      "The scheduled system maintenance has been completed successfully.",
    timeAgo: "3 hours ago",
  },
  {
    title: "Health Seminar",
    description: "A health seminar on diabetes management was conducted.",
    timeAgo: "5 hours ago",
  },
  {
    title: "Emergency Surgery",
    description: "Emergency surgery was performed on patient Bob Green.",
    timeAgo: "7 hours ago",
  },
  {
    title: "Vaccination Drive",
    description: "A vaccination drive was held in the community center.",
    timeAgo: "9 hours ago",
  },
  {
    title: "Medical Records Updated",
    description: "Medical records for patient Carol Davis have been updated.",
    timeAgo: "10 hours ago",
  },
];

export const MEDCONNECT_DASHBOARD_NOTIFICATIONS = [
  {
    type: "Appointment Scheduled",
    title: "Appointment has been scheduled",
    description:
      "An appointment has been scheduled for Jane Smith with Dr. Johnson on 12th June at 3 PM.",
    timeAgo: "9 min ago",
    typeColor: "#00ff00",
  },
  {
    type: "New Patient Added",
    title: "New Patient has been added successfully",
    description:
      "A new patient, John Doe, has been registered into the system. Please ensure all details are verified and updated.",
    timeAgo: "30 min ago",
    typeColor: "#ff0000",
  },
  {
    type: "System Maintenance",
    title: "Scheduled System Maintenance",
    description:
      "The system will undergo maintenance on 15th June from 1 AM to 3 AM. Please save your work to avoid data loss.",
    timeAgo: "1 hour ago",
    typeColor: "#0000ff",
  },
  {
    type: "Training Session",
    title: "CPR Training Session",
    description:
      "A CPR training session will be held on 20th June at 10 AM in the training room. All staff are encouraged to attend.",
    timeAgo: "2 hours ago",
    typeColor: "#ffa500",
  },
  {
    type: "Patient Discharged",
    title: "Patient Discharge Notice",
    description:
      "Patient Carol White has been successfully discharged. Ensure all discharge paperwork is completed.",
    timeAgo: "3 hours ago",
    typeColor: "#ff0000",
  },
  {
    type: "System Update",
    title: "System Update Completed",
    description:
      "The system update has been completed successfully. Please restart your devices to apply the changes.",
    timeAgo: "4 hours ago",
    typeColor: "#0000ff",
  },
  {
    type: "Community Event",
    title: "Health Fair Participation",
    description:
      "Our hospital will be participating in the community health fair on 30th June. Volunteers are needed. Sign up at the front desk.",
    timeAgo: "5 hours ago",
    typeColor: "#ffa500",
  },
  {
    type: "Emergency Alert",
    title: "Emergency Surgery Required",
    description:
      "Patient Bob Brown requires emergency surgery. Dr. Patel has been notified and is preparing for the procedure.",
    timeAgo: "6 hours ago",
    typeColor: "#ff0000",
  },
  {
    type: "Appointment Reminder",
    title: "Appointment Reminder",
    description:
      "Reminder: Patient Michael Davis has an appointment with Dr. Patel tomorrow at 2 PM.",
    timeAgo: "7 hours ago",
    typeColor: "#00ff00",
  },
  {
    type: "Security Alert",
    title: "Security Update",
    description:
      "A security update has been applied to the hospital network. Please restart your devices to ensure the update is applied.",
    timeAgo: "8 hours ago",
    typeColor: "#0000ff",
  },
  {
    type: "Patient Feedback Received",
    title: "Positive Patient Feedback",
    description:
      "We have received positive feedback from patient Emily Brown. Great job team! Keep up the excellent work.",
    timeAgo: "9 hours ago",
    typeColor: "#ff0000",
  },
  {
    type: "Follow-up Scheduled",
    title: "Follow-up Appointment Scheduled",
    description:
      "A follow-up appointment has been scheduled for patient David Brown with Dr. Murphy on 20th June.",
    timeAgo: "10 hours ago",
    typeColor: "#00ff00",
  },
  {
    type: "Staff Meeting Reminder",
    title: "Staff Meeting at 5 PM",
    description:
      "Reminder: There is a staff meeting scheduled today at 5 PM in the conference room. Attendance is mandatory.",
    timeAgo: "11 hours ago",
    typeColor: "#ffa500",
  },
  {
    type: "System Downtime Alert",
    title: "System Downtime Alert",
    description:
      "The system will be down for an update on 18th June from 12 AM to 2 AM. Please plan your tasks accordingly.",
    timeAgo: "12 hours ago",
    typeColor: "#0000ff",
  },
  {
    type: "Appointment Rescheduled",
    title: "Appointment has been rescheduled",
    description:
      "The appointment for patient Alice Johnson with Dr. Lee has been rescheduled to 15th June at 10 AM.",
    timeAgo: "13 hours ago",
    typeColor: "#00ff00",
  },
  {
    type: "New Equipment Arrived",
    title: "New MRI Machine Installed",
    description:
      "A new MRI machine has been installed in the radiology department. Training sessions will be conducted next week.",
    timeAgo: "14 hours ago",
    typeColor: "#ffa500",
  },
  {
    type: "Patient Transfer",
    title: "Patient Transfer Notice",
    description:
      "Patient Sarah Davis has been transferred to another facility for specialized care. Ensure all records are updated.",
    timeAgo: "15 hours ago",
    typeColor: "#ff0000",
  },
  {
    type: "Appointment Canceled",
    title: "Appointment Canceled",
    description:
      "The appointment for patient Sarah Williams with Dr. Smith on 10th June has been canceled.",
    timeAgo: "16 hours ago",
    typeColor: "#00ff00",
  },
  {
    type: "System Backup Completed",
    title: "System Backup Completed",
    description:
      "The scheduled system backup has been completed successfully. All data is secure.",
    timeAgo: "17 hours ago",
    typeColor: "#0000ff",
  },
  {
    type: "Fundraising Event",
    title: "Charity Gala Announcement",
    description:
      "Join us for the annual charity gala on 5th July. All proceeds will go towards hospital improvements.",
    timeAgo: "18 hours ago",
    typeColor: "#ffa500",
  },
];

export const MEDCONNECT_DASHBOARD_HELP_TICKETS = [
  {
    ticketId: "T001",
    subject: "System Update Required",
    dateInitiated: "2024-05-01",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-05",
  },
  {
    ticketId: "T002",
    subject: "Network Issue in Block A",
    dateInitiated: "2024-05-03",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T003",
    subject: "New User Account Setup",
    dateInitiated: "2024-05-05",
    status: "On Hold",
    statusColor: "#ffa500",
    dateCompleted: "",
  },
  {
    ticketId: "T004",
    subject: "Printer Not Working",
    dateInitiated: "2024-05-07",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-10",
  },
  {
    ticketId: "T005",
    subject: "Email Configuration Issue",
    dateInitiated: "2024-05-09",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T006",
    subject: "Software Installation Request",
    dateInitiated: "2024-05-11",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-14",
  },
  {
    ticketId: "T007",
    subject: "Server Maintenance",
    dateInitiated: "2024-05-13",
    status: "On Hold",
    statusColor: "#ffa500",
    dateCompleted: "",
  },
  {
    ticketId: "T008",
    subject: "Data Backup Failure",
    dateInitiated: "2024-05-15",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T009",
    subject: "Firewall Configuration",
    dateInitiated: "2024-05-17",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-20",
  },
  {
    ticketId: "T010",
    subject: "VPN Connectivity Issue",
    dateInitiated: "2024-05-19",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T011",
    subject: "Password Reset",
    dateInitiated: "2024-05-21",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-21",
  },
  {
    ticketId: "T012",
    subject: "Laptop Repair",
    dateInitiated: "2024-05-23",
    status: "On Hold",
    statusColor: "#ffa500",
    dateCompleted: "",
  },
  {
    ticketId: "T013",
    subject: "Database Migration",
    dateInitiated: "2024-05-25",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T014",
    subject: "User Training Session",
    dateInitiated: "2024-05-27",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-05-28",
  },
  {
    ticketId: "T015",
    subject: "Application Crash Issue",
    dateInitiated: "2024-05-29",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T016",
    subject: "Office Move Support",
    dateInitiated: "2024-05-31",
    status: "On Hold",
    statusColor: "#ffa500",
    dateCompleted: "",
  },
  {
    ticketId: "T017",
    subject: "Network Upgrade",
    dateInitiated: "2024-06-02",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T018",
    subject: "Email Spam Filtering",
    dateInitiated: "2024-06-04",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-06-05",
  },
  {
    ticketId: "T019",
    subject: "New Hardware Procurement",
    dateInitiated: "2024-06-06",
    status: "In Progress",
    statusColor: "#ff0000",
    dateCompleted: "",
  },
  {
    ticketId: "T020",
    subject: "Security Patch Update",
    dateInitiated: "2024-06-08",
    status: "Completed",
    statusColor: "#00ff00",
    dateCompleted: "2024-06-09",
  },
];

export const MEDCONNECT_SUPER_ADMIN_DASHBOARD_COMPOUNDS = [
  {
    compoundName: "Korle Bu Teaching Hospital",
    lastLoggedIn: "2024-05-10",
    address: "Guggisberg Ave, Accra",
    district: "Ablekuma South",
    region: "Greater Accra",
  },
  {
    compoundName: "Komfo Anokye Teaching Hospital",
    lastLoggedIn: "2024-06-12",
    address: "Okomfo Anokye Rd, Kumasi",
    district: "Subin",
    region: "Ashanti",
  },
  {
    compoundName: "Tamale Teaching Hospital",
    lastLoggedIn: "2024-05-15",
    address: "Off Hospital Rd, Tamale",
    district: "Tamale Central",
    region: "Northern",
  },
  {
    compoundName: "Cape Coast Teaching Hospital",
    lastLoggedIn: "2024-06-05",
    address: "Cape Coast",
    district: "Cape Coast",
    region: "Central",
  },
  {
    compoundName: "Ho Teaching Hospital",
    lastLoggedIn: "2024-04-25",
    address: "Ho",
    district: "Ho Municipal",
    region: "Volta",
  },
  {
    compoundName: "Bolgatanga Regional Hospital",
    lastLoggedIn: "2024-05-20",
    address: "Bolgatanga",
    district: "Bolgatanga Municipal",
    region: "Upper East",
  },
  {
    compoundName: "Wa Regional Hospital",
    lastLoggedIn: "2024-06-01",
    address: "Wa",
    district: "Wa Municipal",
    region: "Upper West",
  },
  {
    compoundName: "Koforidua Regional Hospital",
    lastLoggedIn: "2024-05-28",
    address: "Koforidua",
    district: "New Juaben South",
    region: "Eastern",
  },
  {
    compoundName: "Effia Nkwanta Regional Hospital",
    lastLoggedIn: "2024-05-10",
    address: "Sekondi-Takoradi",
    district: "Sekondi-Takoradi",
    region: "Western",
  },
  {
    compoundName: "Ridge Hospital",
    lastLoggedIn: "2024-06-10",
    address: "Ridge, Accra",
    district: "Osu Klottey",
    region: "Greater Accra",
  },
  {
    compoundName: "37 Military Hospital",
    lastLoggedIn: "2024-05-18",
    address: "Accra",
    district: "Ayawaso West",
    region: "Greater Accra",
  },
  {
    compoundName: "Sunyani Regional Hospital",
    lastLoggedIn: "2024-06-07",
    address: "Sunyani",
    district: "Sunyani Municipal",
    region: "Bono",
  },
  {
    compoundName: "Tema General Hospital",
    lastLoggedIn: "2024-05-22",
    address: "Tema",
    district: "Tema Metropolitan",
    region: "Greater Accra",
  },
  {
    compoundName: "Axim Government Hospital",
    lastLoggedIn: "2024-05-25",
    address: "Axim",
    district: "Nzema East",
    region: "Western",
  },
  {
    compoundName: "Holy Family Hospital",
    lastLoggedIn: "2024-06-03",
    address: "Techiman",
    district: "Techiman Municipal",
    region: "Bono East",
  },
  {
    compoundName: "St. Theresa's Hospital",
    lastLoggedIn: "2024-05-30",
    address: "Nandom",
    district: "Nandom",
    region: "Upper West",
  },
  {
    compoundName: "St. John's Hospital and Fertility Centre",
    lastLoggedIn: "2024-06-06",
    address: "Sekondi",
    district: "Sekondi-Takoradi",
    region: "Western",
  },
  {
    compoundName: "Agogo Presbyterian Hospital",
    lastLoggedIn: "2024-05-12",
    address: "Agogo",
    district: "Asante Akim North",
    region: "Ashanti",
  },
  {
    compoundName: "Ankaful Psychiatric Hospital",
    lastLoggedIn: "2024-06-04",
    address: "Ankaful",
    district: "Komenda/Edina/Eguafo/Abirem",
    region: "Central",
  },
  {
    compoundName: "St. Dominic's Hospital",
    lastLoggedIn: "2024-05-16",
    address: "Akwatia",
    district: "Denkyembuor",
    region: "Eastern",
  },
];

export const MEDCONNECT_SUPER_ADMIN_DASHBOARD_COMPOUNDS_WITH_ACTIONS = [
  {
    compoundName: "Korle Bu Teaching Hospital",
    compoundId: "GH001",
    location: "Guggisberg Ave, Accra",
    region: "Greater Accra",
  },
  {
    compoundName: "Komfo Anokye Teaching Hospital",
    compoundId: "GH002",
    location: "Okomfo Anokye Rd, Kumasi",
    region: "Ashanti",
  },
  {
    compoundName: "Tamale Teaching Hospital",
    compoundId: "GH003",
    location: "Off Hospital Rd, Tamale",
    region: "Northern",
  },
  {
    compoundName: "Cape Coast Teaching Hospital",
    compoundId: "GH004",
    location: "Cape Coast",
    region: "Central",
  },
  {
    compoundName: "Ho Teaching Hospital",
    compoundId: "GH005",
    location: "Ho",
    region: "Volta",
  },
  {
    compoundName: "Bolgatanga Regional Hospital",
    compoundId: "GH006",
    location: "Bolgatanga",
    region: "Upper East",
  },
  {
    compoundName: "Wa Regional Hospital",
    compoundId: "GH007",
    location: "Wa",
    region: "Upper West",
  },
  {
    compoundName: "Koforidua Regional Hospital",
    compoundId: "GH008",
    location: "Koforidua",
    region: "Eastern",
  },
  {
    compoundName: "Effia Nkwanta Regional Hospital",
    compoundId: "GH009",
    location: "Sekondi-Takoradi",
    region: "Western",
  },
  {
    compoundName: "Ridge Hospital",
    compoundId: "GH010",
    location: "Ridge, Accra",
    region: "Greater Accra",
  },
  {
    compoundName: "37 Military Hospital",
    compoundId: "GH011",
    location: "Accra",
    region: "Greater Accra",
  },
  {
    compoundName: "Sunyani Regional Hospital",
    compoundId: "GH012",
    location: "Sunyani",
    region: "Bono",
  },
  {
    compoundName: "Tema General Hospital",
    compoundId: "GH013",
    location: "Tema",
    region: "Greater Accra",
  },
  {
    compoundName: "Axim Government Hospital",
    compoundId: "GH014",
    location: "Axim",
    region: "Western",
  },
  {
    compoundName: "Holy Family Hospital",
    compoundId: "GH015",
    location: "Techiman",
    region: "Bono East",
  },
];

export const MEDCONNECT_DASHBOARD_PATIENTS = [
  {
    patientID: "MDCKWP001",
    patientName: "Kwame Mensah",
    age: 45,
    gender: "male",
    bloodGroup: "A+",
    phoneNumber: "+233 24 123 4567",
    dateAdded: "2023-06-14",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    patientID: "MDCAPP002",
    patientName: "Akua Nyamekye",
    age: 30,
    gender: "female",
    bloodGroup: "B-",
    phoneNumber: "+233 24 234 5678",
    dateAdded: "2023-05-20",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    patientID: "MDCYBP003",
    patientName: "Yaw Boateng",
    age: 60,
    gender: "male",
    bloodGroup: "O+",
    phoneNumber: "+233 24 345 6789",
    dateAdded: "2023-04-25",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    patientID: "MDCASE004",
    patientName: "Ama Serwaa",
    age: 27,
    gender: "female",
    bloodGroup: "AB-",
    phoneNumber: "+233 24 456 7890",
    dateAdded: "2023-03-18",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    patientID: "MDCKOP005",
    patientName: "Kofi Owusu",
    age: 50,
    gender: "male",
    bloodGroup: "B+",
    phoneNumber: "+233 24 567 8901",
    dateAdded: "2023-02-22",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    patientID: "MDCABP006",
    patientName: "Abena Osei",
    age: 34,
    gender: "female",
    bloodGroup: "O-",
    phoneNumber: "+233 24 678 9012",
    dateAdded: "2023-01-30",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    patientID: "MDCKAP007",
    patientName: "Kojo Agyeman",
    age: 41,
    gender: "male",
    bloodGroup: "A-",
    phoneNumber: "+233 24 789 0123",
    dateAdded: "2023-06-01",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    patientID: "MDCEAP008",
    patientName: "Efua Adjei",
    age: 29,
    gender: "female",
    bloodGroup: "AB+",
    phoneNumber: "+233 24 890 1234",
    dateAdded: "2023-05-15",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    patientID: "MDCYKP009",
    patientName: "Yaw Kyei",
    age: 53,
    gender: "male",
    bloodGroup: "A+",
    phoneNumber: "+233 24 901 2345",
    dateAdded: "2023-04-10",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    patientID: "MDCEGP010",
    patientName: "Esi Gyamfi",
    age: 40,
    gender: "female",
    bloodGroup: "B-",
    phoneNumber: "+233 24 012 3456",
    dateAdded: "2023-03-28",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    patientID: "MDCKNP011",
    patientName: "Kwesi Nkrumah",
    age: 37,
    gender: "male",
    bloodGroup: "O+",
    phoneNumber: "+233 24 123 4568",
    dateAdded: "2023-02-14",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    patientID: "MDCKAP012",
    patientName: "Akosua Yeboah",
    age: 33,
    gender: "female",
    bloodGroup: "AB-",
    phoneNumber: "+233 24 234 5679",
    dateAdded: "2023-01-05",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    patientID: "MDCYAP013",
    patientName: "Yaw Amankwa",
    age: 52,
    gender: "male",
    bloodGroup: "B+",
    phoneNumber: "+233 24 345 6780",
    dateAdded: "2023-06-10",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    patientID: "MDCAOP014",
    patientName: "Ama Obeng",
    age: 26,
    gender: "female",
    bloodGroup: "O-",
    phoneNumber: "+233 24 456 7891",
    dateAdded: "2023-05-07",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    patientID: "MDCKDP015",
    patientName: "Kofi Darko",
    age: 48,
    gender: "male",
    bloodGroup: "A-",
    phoneNumber: "+233 24 567 8902",
    dateAdded: "2023-04-15",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    patientID: "MDCABP016",
    patientName: "Abena Kumi",
    age: 39,
    gender: "female",
    bloodGroup: "AB+",
    phoneNumber: "+233 24 678 9013",
    dateAdded: "2023-03-11",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    patientID: "MDCKAP017",
    patientName: "Kwame Anane",
    age: 55,
    gender: "male",
    bloodGroup: "A+",
    phoneNumber: "+233 24 789 0124",
    dateAdded: "2023-02-20",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    patientID: "MDCAPP018",
    patientName: "Akua Agyapong",
    age: 42,
    gender: "female",
    bloodGroup: "B-",
    phoneNumber: "+233 24 890 1235",
    dateAdded: "2023-01-09",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    patientID: "MDCYOP019",
    patientName: "Yaw Opoku",
    age: 31,
    gender: "male",
    bloodGroup: "O+",
    phoneNumber: "+233 24 901 2346",
    dateAdded: "2023-06-08",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    patientID: "MDCEOP020",
    patientName: "Efua Owusu",
    age: 36,
    gender: "female",
    bloodGroup: "AB-",
    phoneNumber: "+233 24 012 3457",
    dateAdded: "2023-05-18",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];

export const MEDCONNECT_DASHBOARD_APPOINTEMENTS = [
  {
    time: "09:00 AM",
    date: "2024-06-01",
    patientName: "Kwame Mensah",
    age: 45,
    phoneNumber: "+233 24 123 4567",
    assignedHO: "Dr. Yaw Boateng",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "10:30 AM",
    date: "2024-06-02",
    patientName: "Akua Nyamekye",
    age: 30,
    phoneNumber: "+233 24 234 5678",
    assignedHO: "Dr. Ama Serwaa",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "11:15 AM",
    date: "2024-06-03",
    patientName: "Yaw Boateng",
    age: 60,
    phoneNumber: "+233 24 345 6789",
    assignedHO: "Dr. Kojo Agyeman",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "02:00 PM",
    date: "2024-06-04",
    patientName: "Ama Serwaa",
    age: 27,
    phoneNumber: "+233 24 456 7890",
    assignedHO: "Dr. Efua Adjei",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "03:30 PM",
    date: "2024-06-05",
    patientName: "Kofi Owusu",
    age: 50,
    phoneNumber: "+233 24 567 8901",
    assignedHO: "Dr. Kofi Darko",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "08:45 AM",
    date: "2024-06-06",
    patientName: "Abena Osei",
    age: 34,
    phoneNumber: "+233 24 678 9012",
    assignedHO: "Dr. Abena Kumi",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "09:30 AM",
    date: "2024-06-07",
    patientName: "Kojo Agyeman",
    age: 41,
    phoneNumber: "+233 24 789 0123",
    assignedHO: "Dr. Kwame Anane",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "10:00 AM",
    date: "2024-06-08",
    patientName: "Efua Adjei",
    age: 29,
    phoneNumber: "+233 24 890 1234",
    assignedHO: "Dr. Akua Agyapong",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "11:45 AM",
    date: "2024-06-09",
    patientName: "Yaw Kyei",
    age: 53,
    phoneNumber: "+233 24 901 2345",
    assignedHO: "Dr. Yaw Opoku",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "01:30 PM",
    date: "2024-06-10",
    patientName: "Esi Gyamfi",
    age: 40,
    phoneNumber: "+233 24 012 3456",
    assignedHO: "Dr. Efua Owusu",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "02:15 PM",
    date: "2024-06-11",
    patientName: "Kwesi Nkrumah",
    age: 37,
    phoneNumber: "+233 24 123 4568",
    assignedHO: "Dr. Kwame Mensah",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "03:00 PM",
    date: "2024-06-12",
    patientName: "Akosua Yeboah",
    age: 33,
    phoneNumber: "+233 24 234 5679",
    assignedHO: "Dr. Akua Nyamekye",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "04:30 PM",
    date: "2024-06-13",
    patientName: "Yaw Amankwa",
    age: 52,
    phoneNumber: "+233 24 345 6780",
    assignedHO: "Dr. Yaw Boateng",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "08:00 AM",
    date: "2024-06-14",
    patientName: "Ama Obeng",
    age: 26,
    phoneNumber: "+233 24 456 7891",
    assignedHO: "Dr. Ama Serwaa",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "09:15 AM",
    date: "2024-06-15",
    patientName: "Kofi Darko",
    age: 48,
    phoneNumber: "+233 24 567 8902",
    assignedHO: "Dr. Kojo Agyeman",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "10:45 AM",
    date: "2024-06-16",
    patientName: "Abena Kumi",
    age: 39,
    phoneNumber: "+233 24 678 9013",
    assignedHO: "Dr. Efua Adjei",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "11:30 AM",
    date: "2024-06-17",
    patientName: "Kwame Anane",
    age: 55,
    phoneNumber: "+233 24 789 0124",
    assignedHO: "Dr. Kofi Darko",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "12:00 PM",
    date: "2024-06-18",
    patientName: "Akua Agyapong",
    age: 42,
    phoneNumber: "+233 24 890 1235",
    assignedHO: "Dr. Abena Kumi",
    status: "New",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "01:00 PM",
    date: "2024-06-19",
    patientName: "Yaw Opoku",
    age: 31,
    phoneNumber: "+233 24 901 2346",
    assignedHO: "Dr. Kwame Anane",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
  {
    time: "02:45 PM",
    date: "2024-06-20",
    patientName: "Efua Owusu",
    age: 36,
    phoneNumber: "+233 24 012 3457",
    assignedHO: "Dr. Akua Agyapong",
    status: "Completed",
    patientID: `MDCPA${Math.floor(Math.random() * 1000)}`,
  },
];

export const MEDCONNECT_DASHBOARD_DIAGNOSTIC_SUPPORT = [
  {
    id: "dsc1",
    compoundId: "MDK001",
    title: "Fever and Headache",
    description: "Patient is experiencing high fever and severe headache.",
    time: "10:30 AM",
    chats: [
      {
        doctor: "Dr. Yaw Boateng",
        message: "Good morning, can you describe your symptoms?",
        time: "10:30 AM",
      },
      {
        user: "Ama Serwaa",
        message:
          "I've been having a high fever and severe headache since last night.",
        time: "10:32 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message: "Any other symptoms like nausea or dizziness?",
        time: "10:35 AM",
      },
      {
        user: "Ama Serwaa",
        message: "Yes, I've been feeling a bit dizzy.",
        time: "10:37 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message:
          "I recommend taking paracetamol and resting. If the symptoms persist, visit the clinic.",
        time: "10:40 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message: "Good morning, can you describe your symptoms?",
        time: "10:30 AM",
      },
      {
        user: "Ama Serwaa",
        message:
          "I've been having a high fever and severe headache since last night.",
        time: "10:32 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message: "Any other symptoms like nausea or dizziness?",
        time: "10:35 AM",
      },
      {
        user: "Ama Serwaa",
        message: "Yes, I've been feeling a bit dizzy.",
        time: "10:37 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message:
          "I recommend taking paracetamol and resting. If the symptoms persist, visit the clinic.",
        time: "10:40 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message: "Good morning, can you describe your symptoms?",
        time: "10:30 AM",
      },
      {
        user: "Ama Serwaa",
        message:
          "I've been having a high fever and severe headache since last night.",
        time: "10:32 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message: "Any other symptoms like nausea or dizziness?",
        time: "10:35 AM",
      },
      {
        user: "Ama Serwaa",
        message: "Yes, I've been feeling a bit dizzy.",
        time: "10:37 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message:
          "I recommend taking paracetamol and resting. If the symptoms persist, visit the clinic.",
        time: "10:40 AM",
      },
    ],
  },
  {
    id: "dsc2",
    compoundId: "MDK002",
    title: "Stomach Pain",
    description: "Patient reports severe stomach pain and discomfort.",
    time: "01:45 PM",
    chats: [
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Hello, what seems to be the problem?",
        time: "01:45 PM",
      },
      {
        user: "Kofi Owusu",
        message: "I've been having severe stomach pain since this morning.",
        time: "01:47 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Have you eaten anything unusual or felt this pain before?",
        time: "01:50 PM",
      },
      {
        user: "Kofi Owusu",
        message:
          "No, nothing unusual. This is the first time I'm experiencing this.",
        time: "01:52 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message:
          "Try to drink plenty of water and avoid solid foods for a few hours. If the pain worsens, visit the hospital.",
        time: "01:55 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Hello, what seems to be the problem?",
        time: "01:45 PM",
      },
      {
        user: "Kofi Owusu",
        message: "I've been having severe stomach pain since this morning.",
        time: "01:47 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Have you eaten anything unusual or felt this pain before?",
        time: "01:50 PM",
      },
      {
        user: "Kofi Owusu",
        message:
          "No, nothing unusual. This is the first time I'm experiencing this.",
        time: "01:52 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message:
          "Try to drink plenty of water and avoid solid foods for a few hours. If the pain worsens, visit the hospital.",
        time: "01:55 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Hello, what seems to be the problem?",
        time: "01:45 PM",
      },
      {
        user: "Kofi Owusu",
        message: "I've been having severe stomach pain since this morning.",
        time: "01:47 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Have you eaten anything unusual or felt this pain before?",
        time: "01:50 PM",
      },
      {
        user: "Kofi Owusu",
        message:
          "No, nothing unusual. This is the first time I'm experiencing this.",
        time: "01:52 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message:
          "Try to drink plenty of water and avoid solid foods for a few hours. If the pain worsens, visit the hospital.",
        time: "01:55 PM",
      },
    ],
  },
  {
    id: "dsc3",
    compoundId: "MDK003",
    title: "Skin Rash",
    description: "Patient has developed a red, itchy rash on the arms.",
    time: "09:15 AM",
    chats: [
      {
        doctor: "Dr. Kojo Agyeman",
        message: "Good morning, how can I assist you today?",
        time: "09:15 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I've developed a red, itchy rash on my arms.",
        time: "09:17 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Have you used any new products or been in contact with any allergens?",
        time: "09:20 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I started using a new lotion a couple of days ago.",
        time: "09:22 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Stop using the lotion and apply hydrocortisone cream to the rash. If it doesn't improve, please see a dermatologist.",
        time: "09:25 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message: "Good morning, how can I assist you today?",
        time: "09:15 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I've developed a red, itchy rash on my arms.",
        time: "09:17 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Have you used any new products or been in contact with any allergens?",
        time: "09:20 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I started using a new lotion a couple of days ago.",
        time: "09:22 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Stop using the lotion and apply hydrocortisone cream to the rash. If it doesn't improve, please see a dermatologist.",
        time: "09:25 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message: "Good morning, how can I assist you today?",
        time: "09:15 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I've developed a red, itchy rash on my arms.",
        time: "09:17 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Have you used any new products or been in contact with any allergens?",
        time: "09:20 AM",
      },
      {
        user: "Esi Gyamfi",
        message: "I started using a new lotion a couple of days ago.",
        time: "09:22 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Stop using the lotion and apply hydrocortisone cream to the rash. If it doesn't improve, please see a dermatologist.",
        time: "09:25 AM",
      },
    ],
  },
  {
    id: "dsc4",
    compoundId: "MDK004",
    title: "Back Pain",
    description: "Patient complains of lower back pain for the past few days.",
    time: "02:30 PM",
    chats: [
      {
        doctor: "Dr. Efua Adjei",
        message: "Hello, what seems to be the issue?",
        time: "02:30 PM",
      },
      {
        user: "Yaw Amankwa",
        message: "I've been having lower back pain for the past few days.",
        time: "02:32 PM",
      },
      {
        doctor: "Dr. Efua Adjei",
        message: "Did you lift anything heavy or make any sudden movements?",
        time: "02:35 PM",
      },
      {
        user: "Yaw Amankwa",
        message: "I did move some heavy furniture over the weekend.",
        time: "02:37 PM",
      },
      {
        doctor: "Dr. Efua Adjei",
        message:
          "Apply ice to the affected area and take an over-the-counter pain reliever. If the pain persists, schedule an appointment.",
        time: "02:40 PM",
      },
    ],
  },
  {
    id: "dsc5",
    compoundId: "MDK005",
    title: "Sore Throat",
    description: "Patient has a sore throat and difficulty swallowing.",
    time: "11:00 AM",
    chats: [
      {
        doctor: "Dr. Kofi Darko",
        message: "Good morning, what brings you here today?",
        time: "11:00 AM",
      },
      {
        user: "Ama Obeng",
        message: "I have a sore throat and difficulty swallowing.",
        time: "11:02 AM",
      },
      {
        doctor: "Dr. Kofi Darko",
        message: "Do you have a fever or any other symptoms?",
        time: "11:05 AM",
      },
      {
        user: "Ama Obeng",
        message: "No fever, just the sore throat.",
        time: "11:07 AM",
      },
      {
        doctor: "Dr. Kofi Darko",
        message:
          "Gargle with warm salt water and stay hydrated. If it doesn't improve in a few days, visit the clinic.",
        time: "11:10 AM",
      },
    ],
  },
  {
    id: "dsc6",
    compoundId: "MDK006",
    title: "Chest Pain",
    description: "Patient experiencing intermittent chest pain.",
    time: "03:45 PM",
    chats: [
      {
        doctor: "Dr. Abena Kumi",
        message: "Hello, how can I help you today?",
        time: "03:45 PM",
      },
      {
        user: "Kwame Anane",
        message: "I've been having intermittent chest pain.",
        time: "03:47 PM",
      },
      {
        doctor: "Dr. Abena Kumi",
        message:
          "Is the pain sharp or dull, and does it radiate to other parts of your body?",
        time: "03:50 PM",
      },
      {
        user: "Kwame Anane",
        message: "It's a dull pain and sometimes it radiates to my left arm.",
        time: "03:52 PM",
      },
      {
        doctor: "Dr. Abena Kumi",
        message:
          "Please visit the nearest hospital immediately for an ECG and further evaluation.",
        time: "03:55 PM",
      },
    ],
  },
  {
    id: "dsc7",
    compoundId: "MDK007",
    title: "Allergic Reaction",
    description: "Patient reports swelling and itching after eating seafood.",
    time: "12:30 PM",
    chats: [
      {
        doctor: "Dr. Kwame Mensah",
        message: "Good afternoon, how can I assist?",
        time: "12:30 PM",
      },
      {
        user: "Akua Agyapong",
        message: "I have swelling and itching after eating seafood.",
        time: "12:32 PM",
      },
      {
        doctor: "Dr. Kwame Mensah",
        message: "Do you have any difficulty breathing or other symptoms?",
        time: "12:35 PM",
      },
      {
        user: "Akua Agyapong",
        message: "No, just the swelling and itching.",
        time: "12:37 PM",
      },
      {
        doctor: "Dr. Kwame Mensah",
        message:
          "Take an antihistamine like Benadryl and avoid seafood. If symptoms worsen, seek emergency care.",
        time: "12:40 PM",
      },
    ],
  },
  {
    id: "dsc8",
    compoundId: "MDK008",
    title: "Joint Pain",
    description:
      "Patient complains of joint pain and stiffness in the mornings.",
    time: "08:30 AM",
    chats: [
      {
        doctor: "Dr. Yaw Boateng",
        message: "Good morning, what can I help you with today?",
        time: "08:30 AM",
      },
      {
        user: "Yaw Opoku",
        message: "I've been having joint pain and stiffness in the mornings.",
        time: "08:32 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message:
          "Which joints are affected, and how long have you had these symptoms?",
        time: "08:35 AM",
      },
      {
        user: "Yaw Opoku",
        message: "Mostly my knees and hands. It's been about a week.",
        time: "08:37 AM",
      },
      {
        doctor: "Dr. Yaw Boateng",
        message:
          "Try taking an over-the-counter anti-inflammatory and doing gentle exercises. If it doesn't improve, come in for a check-up.",
        time: "08:40 AM",
      },
    ],
  },
  {
    id: "dsc9",
    compoundId: "MDK009",
    title: "Earache",
    description: "Patient reports ear pain and slight hearing loss.",
    time: "05:00 PM",
    chats: [
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Good evening, what brings you here today?",
        time: "05:00 PM",
      },
      {
        user: "Akosua Yeboah",
        message: "I have ear pain and slight hearing loss.",
        time: "05:02 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message: "Any discharge or other symptoms?",
        time: "05:05 PM",
      },
      {
        user: "Akosua Yeboah",
        message: "No discharge, just the pain and hearing loss.",
        time: "05:07 PM",
      },
      {
        doctor: "Dr. Akua Nyamekye",
        message:
          "Try using ear drops and avoid getting water in your ear. If it doesn't improve, visit the clinic.",
        time: "05:10 PM",
      },
    ],
  },
  {
    id: "dsc10",
    compoundId: "MDK010",
    title: "Cold and Cough",
    description: "Patient experiencing persistent cold and cough.",
    time: "07:45 AM",
    chats: [
      {
        doctor: "Dr. Kojo Agyeman",
        message: "Good morning, how can I help you?",
        time: "07:45 AM",
      },
      {
        user: "Kwesi Nkrumah",
        message: "I've been having a persistent cold and cough.",
        time: "07:47 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message: "How long have you had these symptoms?",
        time: "07:50 AM",
      },
      {
        user: "Kwesi Nkrumah",
        message: "It's been about two weeks.",
        time: "07:52 AM",
      },
      {
        doctor: "Dr. Kojo Agyeman",
        message:
          "Increase your fluid intake and rest. If it doesn't improve, please come in for a check-up.",
        time: "07:55 AM",
      },
    ],
  },
];

export const MEDCONNECT_DASHBOARD_PATIENT_PRESCRIPTIONS = [
  {
    prescriptionFor: "Malaria",
    date: "25th June 2024",
    prescriptionID: "RX12345",
    healthOfficialName: "Dr. John Doe",
    medications: {
      medicationName: "Paracetamol",
      dosage: "500mg",
      frequency: 3, // per day
      duration: "1 week",
    },
    notes: "Patient should stay hydrated and take plenty of rest.",
  },
  {
    prescriptionFor: "Flu",
    date: "20th June 2024",
    prescriptionID: "RX12346",
    healthOfficialName: "Dr. Jane Smith",
    medications: {
      medicationName: "Ibuprofen",
      dosage: "400mg",
      frequency: 2, // per day
      duration: "5 days",
    },
    notes: "Avoid cold drinks and take with food.",
  },
  {
    prescriptionFor: "Hypertension",
    date: "18th June 2024",
    prescriptionID: "RX12347",
    healthOfficialName: "Dr. Michael Brown",
    medications: {
      medicationName: "Lisinopril",
      dosage: "10mg",
      frequency: 1, // per day
      duration: "2 weeks",
    },
    notes: "Monitor blood pressure daily and report any unusual symptoms.",
  },
  {
    prescriptionFor: "Diabetes",
    date: "22nd June 2024",
    prescriptionID: "RX12348",
    healthOfficialName: "Dr. Sarah Johnson",
    medications: {
      medicationName: "Metformin",
      dosage: "500mg",
      frequency: 2, // per day
      duration: "1 month",
    },
    notes: "Maintain a balanced diet and check blood sugar levels regularly.",
  },
  {
    prescriptionFor: "Allergy",
    date: "19th June 2024",
    prescriptionID: "RX12349",
    healthOfficialName: "Dr. William Lee",
    medications: {
      medicationName: "Cetirizine",
      dosage: "10mg",
      frequency: 1, // per day
      duration: "1 week",
    },
    notes: "Avoid allergens and follow up if symptoms persist.",
  },
];

export const MEDCONNECT_DASHBOARD_PATIENT_VISIT_LOGS = [
  {
    logID: "VL9834",
    visitDate: "2024-06-19",
    visitTime: "10:30AM",
    visitPurpose: "Follow up",
    attendingHO: "Dr. John Doe",
    notes: "Patient showing significant improvement.",
  },
  {
    logID: "VL9835",
    visitDate: "2024-06-20",
    visitTime: "11:00AM",
    visitPurpose: "Routine check-up",
    attendingHO: "Dr. Jane Smith",
    notes: "No new issues reported.",
  },
  {
    logID: "VL9836",
    visitDate: "2024-06-21",
    visitTime: "09:15AM",
    visitPurpose: "Blood test results",
    attendingHO: "Dr. Michael Brown",
    notes: "Blood test results normal. Continue current medication.",
  },
  {
    logID: "VL9837",
    visitDate: "2024-06-22",
    visitTime: "02:00PM",
    visitPurpose: "Prescription refill",
    attendingHO: "Dr. Sarah Johnson",
    notes: "Refilled Metformin for diabetes management.",
  },
  {
    logID: "VL9838",
    visitDate: "2024-06-23",
    visitTime: "10:45AM",
    visitPurpose: "Vaccination",
    attendingHO: "Dr. William Lee",
    notes: "Administered annual flu shot.",
  },
  {
    logID: "VL9839",
    visitDate: "2024-06-24",
    visitTime: "01:30PM",
    visitPurpose: "Specialist referral",
    attendingHO: "Dr. Emily Clark",
    notes: "Referred to cardiologist for further evaluation.",
  },
  {
    logID: "VL9840",
    visitDate: "2024-06-25",
    visitTime: "08:00AM",
    visitPurpose: "Blood pressure check",
    attendingHO: "Dr. Daniel Martinez",
    notes: "Blood pressure within normal range. Continue medication.",
  },
  {
    logID: "VL9841",
    visitDate: "2024-06-26",
    visitTime: "12:00PM",
    visitPurpose: "Diabetes management",
    attendingHO: "Dr. Laura White",
    notes: "Adjusted insulin dosage.",
  },
  {
    logID: "VL9842",
    visitDate: "2024-06-27",
    visitTime: "03:45PM",
    visitPurpose: "Allergy consultation",
    attendingHO: "Dr. Kevin Harris",
    notes: "Prescribed new antihistamine.",
  },
  {
    logID: "VL9843",
    visitDate: "2024-06-28",
    visitTime: "09:30AM",
    visitPurpose: "Skin rash evaluation",
    attendingHO: "Dr. Patricia Lewis",
    notes: "Diagnosed with eczema. Provided treatment plan.",
  },
  {
    logID: "VL9844",
    visitDate: "2024-06-29",
    visitTime: "11:15AM",
    visitPurpose: "Annual physical",
    attendingHO: "Dr. Anthony Walker",
    notes: "Overall health is good. Scheduled next visit.",
  },
  {
    logID: "VL9845",
    visitDate: "2024-06-30",
    visitTime: "04:00PM",
    visitPurpose: "Nutrition advice",
    attendingHO: "Dr. Nancy Young",
    notes: "Provided dietary recommendations.",
  },
  {
    logID: "VL9846",
    visitDate: "2024-07-01",
    visitTime: "10:00AM",
    visitPurpose: "Mental health follow-up",
    attendingHO: "Dr. Robert Allen",
    notes: "Patient reports improvement in mood.",
  },
  {
    logID: "VL9847",
    visitDate: "2024-07-02",
    visitTime: "02:30PM",
    visitPurpose: "Post-surgery check-up",
    attendingHO: "Dr. Lisa Scott",
    notes: "Surgical wound healing well.",
  },
  {
    logID: "VL9848",
    visitDate: "2024-07-03",
    visitTime: "01:00PM",
    visitPurpose: "Medication review",
    attendingHO: "Dr. Matthew Turner",
    notes: "Reviewed and adjusted medication plan.",
  },
  {
    logID: "VL9849",
    visitDate: "2024-07-04",
    visitTime: "09:00AM",
    visitPurpose: "Pain management",
    attendingHO: "Dr. Olivia Campbell",
    notes: "Prescribed new pain relief medication.",
  },
  {
    logID: "VL9850",
    visitDate: "2024-07-05",
    visitTime: "11:45AM",
    visitPurpose: "Injury follow-up",
    attendingHO: "Dr. Ethan Roberts",
    notes: "Injury healing well. Advised to continue physical therapy.",
  },
];

export const MEDCONNECT_DASHBOARD_PATIENTS_INVENTORY = [
  {
    id: "MDCIV0001",
    productName: "Albuterol (Salbutamol)",
    productType: "Inhaler",
    inStock: "100 pcs",
    receivedDate: "01 June, 2024",
    expiryDate: "01 Dec, 2024",
    manufacturer: "David's Ltd",
  },
  {
    id: "MDCIV0002",
    productName: "Paracetamol",
    productType: "Tablet",
    inStock: "500 pcs",
    receivedDate: "15 June, 2024",
    expiryDate: "15 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0003",
    productName: "Amoxicillin",
    productType: "Capsule",
    inStock: "300 pcs",
    receivedDate: "10 June, 2024",
    expiryDate: "10 Dec, 2024",
    manufacturer: "Kumasi Pharmaceuticals",
  },
  {
    id: "MDCIV0004",
    productName: "Ibuprofen",
    productType: "Tablet",
    inStock: "200 pcs",
    receivedDate: "05 June, 2024",
    expiryDate: "05 Dec, 2024",
    manufacturer: "Accra Health Ltd",
  },
  {
    id: "MDCIV0005",
    productName: "Metformin",
    productType: "Tablet",
    inStock: "150 pcs",
    receivedDate: "20 June, 2024",
    expiryDate: "20 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0006",
    productName: "Lisinopril",
    productType: "Tablet",
    inStock: "120 pcs",
    receivedDate: "25 June, 2024",
    expiryDate: "25 Dec, 2024",
    manufacturer: "Health Co.",
  },
  {
    id: "MDCIV0007",
    productName: "Atorvastatin",
    productType: "Tablet",
    inStock: "180 pcs",
    receivedDate: "30 June, 2024",
    expiryDate: "30 Dec, 2024",
    manufacturer: "Kumasi Pharmaceuticals",
  },
  {
    id: "MDCIV0008",
    productName: "Omeprazole",
    productType: "Capsule",
    inStock: "220 pcs",
    receivedDate: "02 June, 2024",
    expiryDate: "02 Dec, 2024",
    manufacturer: "Accra Health Ltd",
  },
  {
    id: "MDCIV0009",
    productName: "Ciprofloxacin",
    productType: "Tablet",
    inStock: "140 pcs",
    receivedDate: "18 June, 2024",
    expiryDate: "18 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0010",
    productName: "Losartan",
    productType: "Tablet",
    inStock: "130 pcs",
    receivedDate: "22 June, 2024",
    expiryDate: "22 Dec, 2024",
    manufacturer: "Health Co.",
  },
  {
    id: "MDCIV0011",
    productName: "Hydrochlorothiazide",
    productType: "Tablet",
    inStock: "160 pcs",
    receivedDate: "03 June, 2024",
    expiryDate: "03 Dec, 2024",
    manufacturer: "David's Ltd",
  },
  {
    id: "MDCIV0012",
    productName: "Simvastatin",
    productType: "Tablet",
    inStock: "170 pcs",
    receivedDate: "07 June, 2024",
    expiryDate: "07 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0013",
    productName: "Metoprolol",
    productType: "Tablet",
    inStock: "190 pcs",
    receivedDate: "12 June, 2024",
    expiryDate: "12 Dec, 2024",
    manufacturer: "Kumasi Pharmaceuticals",
  },
  {
    id: "MDCIV0014",
    productName: "Amlodipine",
    productType: "Tablet",
    inStock: "110 pcs",
    receivedDate: "19 June, 2024",
    expiryDate: "19 Dec, 2024",
    manufacturer: "Accra Health Ltd",
  },
  {
    id: "MDCIV0015",
    productName: "Prednisone",
    productType: "Tablet",
    inStock: "210 pcs",
    receivedDate: "24 June, 2024",
    expiryDate: "24 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0016",
    productName: "Warfarin",
    productType: "Tablet",
    inStock: "220 pcs",
    receivedDate: "26 June, 2024",
    expiryDate: "26 Dec, 2024",
    manufacturer: "Health Co.",
  },
  {
    id: "MDCIV0017",
    productName: "Clopidogrel",
    productType: "Tablet",
    inStock: "230 pcs",
    receivedDate: "28 June, 2024",
    expiryDate: "28 Dec, 2024",
    manufacturer: "Kumasi Pharmaceuticals",
  },
  {
    id: "MDCIV0018",
    productName: "Fluticasone",
    productType: "Inhaler",
    inStock: "240 pcs",
    receivedDate: "29 June, 2024",
    expiryDate: "29 Dec, 2024",
    manufacturer: "Accra Health Ltd",
  },
  {
    id: "MDCIV0019",
    productName: "Levothyroxine",
    productType: "Tablet",
    inStock: "250 pcs",
    receivedDate: "30 June, 2024",
    expiryDate: "30 Dec, 2024",
    manufacturer: "Ghana Pharma",
  },
  {
    id: "MDCIV0020",
    productName: "Doxycycline",
    productType: "Capsule",
    inStock: "260 pcs",
    receivedDate: "01 July, 2024",
    expiryDate: "01 Jan, 2025",
    manufacturer: "Health Co.",
  },
];

export const MEDCONNECT_DASHBOARD_PATIENTS_HEALTH_OFFICIALS = [
  {
    staffID: "MDST001",
    firstName: "Kwame",
    lastName: "Mensah",
    gender: "male",
    dob: "1975-05-15",
    contactNumber: "+233 293749273",
    email: "kmensah@healthghana.com",
    position: "Chief Medical Officer",
    location: "Accra",
    dateStarted: "06/10/2024",
  },
  {
    staffID: "MDST002",
    firstName: "Ama",
    lastName: "Kusi",
    gender: "female",
    dob: "1980-08-22",
    contactNumber: "+233 293749274",
    email: "akusiped@healthghana.com",
    position: "Pediatrician",
    location: "Kumasi",
    dateStarted: "07/15/2024",
  },
  {
    staffID: "MDST003",
    firstName: "Yaw",
    lastName: "Adom",
    gender: "male",
    dob: "1978-11-12",
    contactNumber: "+233 293749275",
    email: "yadomcardio@healthghana.com",
    position: "Cardiologist",
    location: "Takoradi",
    dateStarted: "08/20/2024",
  },
  {
    staffID: "MDST004",
    firstName: "Efua",
    lastName: "Badu",
    gender: "female",
    dob: "1985-02-05",
    contactNumber: "+233 293749276",
    email: "efuabneurology@healthghana.com",
    position: "Neurologist",
    location: "Tema",
    dateStarted: "09/25/2024",
  },
  {
    staffID: "MDST005",
    firstName: "Nana",
    lastName: "Opoku",
    gender: "male",
    dob: "1979-03-10",
    contactNumber: "+233 293749277",
    email: "nopokuortho@healthghana.com",
    position: "Orthopedic Surgeon",
    location: "Cape Coast",
    dateStarted: "10/30/2024",
  },
  {
    staffID: "MDST006",
    firstName: "Kofi",
    lastName: "Owusu",
    gender: "male",
    dob: "1983-07-18",
    contactNumber: "+233 293749278",
    email: "kowusugp@healthghana.com",
    position: "General Practitioner",
    location: "Sunyani",
    dateStarted: "11/05/2024",
  },
  {
    staffID: "MDST007",
    firstName: "Adjoa",
    lastName: "Akosua",
    gender: "female",
    dob: "1984-01-24",
    contactNumber: "+233 293749279",
    email: "aakosderm@healthghana.com",
    position: "Dermatologist",
    location: "Koforidua",
    dateStarted: "12/10/2024",
  },
  {
    staffID: "MDST008",
    firstName: "Peter",
    lastName: "Quartey",
    gender: "male",
    dob: "1977-09-30",
    contactNumber: "+233 293749280",
    email: "pquarteyrad@healthghana.com",
    position: "Radiologist",
    location: "Ho",
    dateStarted: "01/15/2024",
  },
  {
    staffID: "MDST009",
    firstName: "Cecilia",
    lastName: "Baah",
    gender: "female",
    dob: "1986-06-14",
    contactNumber: "+233 293749281",
    email: "cbaahonco@healthghana.com",
    position: "Oncologist",
    location: "Bolgatanga",
    dateStarted: "02/20/2024",
  },
  {
    staffID: "MDST010",
    firstName: "Samuel",
    lastName: "Nketia",
    gender: "male",
    dob: "1981-12-01",
    contactNumber: "+233 293749282",
    email: "snketiaendo@healthghana.com",
    position: "Endocrinologist",
    location: "Wa",
    dateStarted: "03/25/2024",
  },
  {
    staffID: "MDST011",
    firstName: "Mansa",
    lastName: "Tetteh",
    gender: "female",
    dob: "1979-04-16",
    contactNumber: "+233 293749283",
    email: "mtettehgyne@healthghana.com",
    position: "Gynecologist",
    location: "Techiman",
    dateStarted: "04/30/2024",
  },
  {
    staffID: "MDST012",
    firstName: "Frank",
    lastName: "Aboagye",
    gender: "male",
    dob: "1985-07-25",
    contactNumber: "+233 293749284",
    email: "faboagyeur@healthghana.com",
    position: "Urologist",
    location: "Tamale",
    dateStarted: "05/05/2024",
  },
  {
    staffID: "MDST013",
    firstName: "Janet",
    lastName: "Sarfo",
    gender: "female",
    dob: "1982-10-10",
    contactNumber: "+233 293749285",
    email: "jsarfopulm@healthghana.com",
    position: "Pulmonologist",
    location: "Sekondi",
    dateStarted: "06/10/2024",
  },
  {
    staffID: "MDST014",
    firstName: "Thomas",
    lastName: "Nyarko",
    gender: "male",
    dob: "1978-05-20",
    contactNumber: "+233 293749286",
    email: "tnyarkonephro@healthghana.com",
    position: "Nephrologist",
    location: "Obuasi",
    dateStarted: "07/15/2024",
  },
  {
    staffID: "MDST015",
    firstName: "Gloria",
    lastName: "Ofori",
    gender: "female",
    dob: "1984-03-22",
    contactNumber: "+233 293749287",
    email: "goforihema@healthghana.com",
    position: "Hematologist",
    location: "Nkawkaw",
    dateStarted: "08/20/2024",
  },
  {
    staffID: "MDST016",
    firstName: "Richard",
    lastName: "Asare",
    gender: "male",
    dob: "1980-11-11",
    contactNumber: "+233 293749288",
    email: "rasaregastro@healthghana.com",
    position: "Gastroenterologist",
    location: "Kasoa",
    dateStarted: "09/25/2024",
  },
  {
    staffID: "MDST017",
    firstName: "Lydia",
    lastName: "Ankomah",
    gender: "female",
    dob: "1977-12-30",
    contactNumber: "+233 293749289",
    email: "lankomahoph@healthghana.com",
    position: "Ophthalmologist",
    location: "Swedru",
    dateStarted: "10/30/2024",
  },
  {
    staffID: "MDST018",
    firstName: "Michael",
    lastName: "Boateng",
    gender: "male",
    dob: "1979-01-17",
    contactNumber: "+233 293749290",
    email: "mboatengpsy@healthghana.com",
    position: "Psychiatrist",
    location: "Elmina",
    dateStarted: "11/05/2024",
  },
  {
    staffID: "MDST019",
    firstName: "Josephine",
    lastName: "Asiedu",
    gender: "female",
    dob: "1986-08-09",
    contactNumber: "+233 293749291",
    email: "jasiedurheuma@healthghana.com",
    position: "Rheumatologist",
    location: "Axim",
    dateStarted: "12/10/2024",
  },
  {
    staffID: "MDST020",
    firstName: "Charles",
    lastName: "Amankwah",
    gender: "male",
    dob: "1983-02-14",
    contactNumber: "+233 293749292",
    email: "camankwahimm@healthghana.com",
    position: "Immunologist",
    location: "Suhum",
    dateStarted: "01/15/2024",
  },
];

export const MEDCONNECT_DASHBOARD_OUTREACH_PROGRAMS = [
  {
    id: "MDCOP001",
    title: "Health Education Workshop on Malaria Prevention",
    description:
      "A comprehensive workshop focused on educating participants about malaria prevention, symptoms, and treatment options. The session will cover the importance of using insecticide-treated nets, recognizing early signs of malaria, and seeking timely medical care.",
    phoneNumber: "+233 243567890",
    targetGroup: "Adults",
    numberOfParticipants: 50,
    location: "Accra",
    programDate: "2024-07-15",
    programStartTime: "10:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Kwame Mensah",
    organization: "Ghana Health Service",
  },
  {
    id: "MDCOP002",
    title: "Nutrition and Healthy Eating Workshop",
    description:
      "Join us for a workshop on nutrition and healthy eating habits. Learn about balanced diets, the role of various nutrients in the body, and how to make healthier food choices. This workshop aims to promote better dietary habits among participants.",
    phoneNumber: "+233 249876543",
    targetGroup: "Teenagers",
    numberOfParticipants: 60,
    location: "Kumasi",
    programDate: "2024-08-10",
    programStartTime: "09:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Ama Kusi",
    organization: "Healthy Living Foundation",
  },
  {
    id: "MDCOP003",
    title: "First Aid and Emergency Response Workshop",
    description:
      "This workshop aims to equip participants with essential first aid skills and emergency response techniques. Topics covered will include CPR, wound management, and handling common emergencies at home or in the workplace.",
    phoneNumber: "+233 207654321",
    targetGroup: "Healthcare Workers",
    numberOfParticipants: 40,
    location: "Takoradi",
    programDate: "2024-09-05",
    programStartTime: "11:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. John Quartey",
    organization: "Red Cross Ghana",
  },
  {
    id: "MDCOP004",
    title: "Mental Health Awareness Workshop",
    description:
      "A workshop dedicated to raising awareness about mental health issues, including depression, anxiety, and stress management. Participants will learn about the importance of mental well-being and strategies to cope with mental health challenges.",
    phoneNumber: "+233 248765432",
    targetGroup: "Young Adults",
    numberOfParticipants: 70,
    location: "Cape Coast",
    programDate: "2024-10-20",
    programStartTime: "01:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Efua Badu",
    organization: "Mental Health Ghana",
  },
  {
    id: "MDCOP005",
    title: "Diabetes Management Workshop",
    description:
      "An informative workshop on diabetes management, focusing on lifestyle changes, medication, and monitoring blood sugar levels. Participants will gain valuable insights into living with diabetes and preventing complications.",
    phoneNumber: "+233 206543210",
    targetGroup: "Elderly",
    numberOfParticipants: 30,
    location: "Tema",
    programDate: "2024-11-15",
    programStartTime: "02:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Nana Opoku",
    organization: "Diabetes Association of Ghana",
  },
  {
    id: "MDCOP006",
    title: "Breast Cancer Awareness Workshop",
    description:
      "A workshop aimed at increasing awareness about breast cancer, its risk factors, early detection, and treatment options. Participants will learn about self-examination techniques and the importance of regular screenings.",
    phoneNumber: "+233 205432109",
    targetGroup: "Women",
    numberOfParticipants: 80,
    location: "Sunyani",
    programDate: "2024-12-01",
    programStartTime: "03:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Adjoa Akosua",
    organization: "Breast Cancer Awareness Ghana",
  },
  {
    id: "MDCOP007",
    title: "HIV/AIDS Education Workshop",
    description:
      "Join us for an educational workshop on HIV/AIDS, where participants will learn about prevention, testing, and treatment options. The workshop aims to reduce stigma and promote awareness about HIV/AIDS in the community.",
    phoneNumber: "+233 204321098",
    targetGroup: "Youth",
    numberOfParticipants: 90,
    location: "Koforidua",
    programDate: "2024-07-25",
    programStartTime: "04:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Mr. Peter Quartey",
    organization: "HIV/AIDS Support Network",
  },
  {
    id: "MDCOP008",
    title: "Childhood Immunization Workshop",
    description:
      "This workshop will provide parents and caregivers with essential information about childhood immunizations, their benefits, and the recommended vaccination schedule. Learn how to protect your children from preventable diseases.",
    phoneNumber: "+233 203210987",
    targetGroup: "Parents",
    numberOfParticipants: 100,
    location: "Bolgatanga",
    programDate: "2024-08-15",
    programStartTime: "10:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Cecilia Baah",
    organization: "Immunization Ghana",
  },
  {
    id: "MDCOP009",
    title: "Healthy Lifestyle Workshop",
    description:
      "An engaging workshop on adopting a healthy lifestyle, covering topics such as regular exercise, balanced nutrition, and stress management. Participants will learn practical tips for maintaining overall well-being.",
    phoneNumber: "+233 202109876",
    targetGroup: "General Public",
    numberOfParticipants: 120,
    location: "Wa",
    programDate: "2024-09-10",
    programStartTime: "09:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Mansa Tetteh",
    organization: "Wellness Ghana",
  },
  {
    id: "MDCOP010",
    title: "Hypertension Awareness Workshop",
    description:
      "A workshop designed to educate participants about hypertension, its risk factors, symptoms, and management. Learn how to monitor blood pressure, make lifestyle changes, and manage hypertension effectively.",
    phoneNumber: "+233 201098765",
    targetGroup: "Middle-Aged Adults",
    numberOfParticipants: 65,
    location: "Techiman",
    programDate: "2024-10-05",
    programStartTime: "11:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Frank Aboagye",
    organization: "Heart Health Ghana",
  },
  {
    id: "MDCOP011",
    title: "Smoking Cessation Workshop",
    description:
      "Join us for a workshop dedicated to helping participants quit smoking. Learn about the health risks of smoking, strategies for quitting, and available support resources. Take the first step towards a smoke-free life.",
    phoneNumber: "+233 200987654",
    targetGroup: "Smokers",
    numberOfParticipants: 40,
    location: "Tamale",
    programDate: "2024-11-20",
    programStartTime: "01:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Mr. Samuel Nketia",
    organization: "Smoke-Free Ghana",
  },
  {
    id: "MDCOP012",
    title: "Asthma Management Workshop",
    description:
      "This workshop aims to educate participants about asthma management, including recognizing triggers, using inhalers correctly, and developing an asthma action plan. Gain valuable insights into living well with asthma.",
    phoneNumber: "+233 200876543",
    targetGroup: "Asthma Patients",
    numberOfParticipants: 55,
    location: "Sekondi",
    programDate: "2024-12-15",
    programStartTime: "02:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Janet Sarfo",
    organization: "Asthma Care Ghana",
  },
  {
    id: "MDCOP013",
    title: "Tuberculosis Awareness Workshop",
    description:
      "A workshop focused on raising awareness about tuberculosis (TB), its symptoms, transmission, and treatment. Participants will learn about the importance of early detection and adhering to the treatment regimen.",
    phoneNumber: "+233 200765432",
    targetGroup: "Healthcare Providers",
    numberOfParticipants: 50,
    location: "Obuasi",
    programDate: "2024-07-30",
    programStartTime: "03:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Thomas Nyarko",
    organization: "TB Control Program Ghana",
  },
  {
    id: "MDCOP014",
    title: "Chronic Disease Management Workshop",
    description:
      "An informative workshop on managing chronic diseases such as diabetes, hypertension, and arthritis. Participants will learn about medication adherence, lifestyle modifications, and regular monitoring to manage their conditions effectively.",
    phoneNumber: "+233 200654321",
    targetGroup: "Chronic Disease Patients",
    numberOfParticipants: 70,
    location: "Nkawkaw",
    programDate: "2024-08-20",
    programStartTime: "04:00 PM",
    image: "https://picsum.photos/200",
    organizerName: "Ms. Gloria Ofori",
    organization: "Chronic Care Ghana",
  },
  {
    id: "MDCOP015",
    title: "Women's Health Workshop",
    description:
      "A workshop dedicated to addressing women's health issues, including reproductive health, menopause, and hormonal changes. Participants will gain valuable insights into maintaining optimal health at different stages of life.",
    phoneNumber: "+233 200543210",
    targetGroup: "Women",
    numberOfParticipants: 85,
    location: "Kasoa",
    programDate: "2024-09-15",
    programStartTime: "10:00 AM",
    image: "https://picsum.photos/200",
    organizerName: "Dr. Richard Asare",
    organization: "Women's Health Ghana",
  },
];

export const MEDCONNECT_DASHBOARD_REPORT_TYPES_SUPER_ADMIN = [
  {
    name: "Patients Report",
    type: "patients",
    reportTypes: [
      { name: "Admission Report", value: "admission report" },
      { name: "Discharge Report", value: "discharge report" },
      { name: "Consultation Report", value: "consultation report" },
      { name: "Treatment Plan Report", value: "treatment plan report" },
    ],
  },
  {
    name: "Appointments Report",
    type: "appointments",
    reportTypes: [
      { name: "Daily Appointment Report", value: "daily appointment report" },
      { name: "Weekly Appointment Report", value: "weekly appointment report" },
      {
        name: "Monthly Appointment Report",
        value: "monthly appointment report",
      },
      {
        name: "Cancelled Appointment Report",
        value: "cancelled appointment report",
      },
    ],
  },
  {
    name: "Inventory Report",
    type: "inventory",
    reportTypes: [
      { name: "Stock Report", value: "stock report" },
      { name: "Usage Report", value: "usage report" },
      { name: "Expiry Report", value: "expiry report" },
      { name: "Purchase Report", value: "purchase report" },
    ],
  },
  {
    name: "Diagnostic Report",
    type: "diagnostic",
    reportTypes: [
      { name: "Radiology Report", value: "radiology report" },
      { name: "Laboratory Report", value: "laboratory report" },
      { name: "Cardiology Report", value: "cardiology report" },
      { name: "Pathology Report", value: "pathology report" },
    ],
  },
  {
    name: "System Performance Report",
    type: "system-performance",
    reportTypes: [
      { name: "Uptime Report", value: "uptime report" },
      { name: "Response Time Report", value: "response time report" },
      { name: "Error Report", value: "error report" },
      { name: "Load Report", value: "load report" },
    ],
  },
  {
    name: "Compound Management Report",
    type: "compound-management",
    reportTypes: [
      { name: "Chemical Inventory Report", value: "chemical inventory report" },
      { name: "Compound Usage Report", value: "compound usage report" },
      { name: "Safety Report", value: "safety report" },
      { name: "Storage Report", value: "storage report" },
    ],
  },
  {
    name: "Outreach Program Report",
    type: "outreach-program",
    reportTypes: [
      { name: "Event Report", value: "event report" },
      { name: "Participation Report", value: "participation report" },
      { name: "Feedback Report", value: "feedback report" },
      { name: "Impact Assessment Report", value: "impact assessment report" },
    ],
  },
];

export const MEDCONNECT_DASHBOARD_REPORT_TYPES_ADMIN = [
  {
    name: "Patients Report",
    type: "patients",
    reportTypes: [
      { name: "Admission Report", value: "admission report" },
      { name: "Discharge Report", value: "discharge report" },
      { name: "Consultation Report", value: "consultation report" },
      { name: "Treatment Plan Report", value: "treatment plan report" },
    ],
  },
  {
    name: "Appointments Report",
    type: "appointments",
    reportTypes: [
      { name: "Daily Appointment Report", value: "daily appointment report" },
      { name: "Weekly Appointment Report", value: "weekly appointment report" },
      {
        name: "Monthly Appointment Report",
        value: "monthly appointment report",
      },
      {
        name: "Cancelled Appointment Report",
        value: "cancelled appointment report",
      },
    ],
  },
  {
    name: "Inventory Report",
    type: "inventory",
    reportTypes: [
      { name: "Stock Report", value: "stock report" },
      { name: "Usage Report", value: "usage report" },
      { name: "Expiry Report", value: "expiry report" },
      { name: "Purchase Report", value: "purchase report" },
    ],
  },
  {
    name: "Diagnostic Report",
    type: "diagnostic",
    reportTypes: [
      { name: "Radiology Report", value: "radiology report" },
      { name: "Laboratory Report", value: "laboratory report" },
      { name: "Cardiology Report", value: "cardiology report" },
      { name: "Pathology Report", value: "pathology report" },
    ],
  },
  {
    name: "Health Officials Report",
    type: "health-officials",
    reportTypes: [
      { name: "Staff Attendance Report", value: "staff attendance report" },
      {
        name: "Performance Evaluation Report",
        value: "performance evaluation report",
      },
      { name: "Training Report", value: "training report" },
      { name: "Certification Report", value: "certification report" },
    ],
  },
  {
    name: "Disease Analysis Report",
    type: "disease-analysis",
    reportTypes: [
      { name: "Infection Report", value: "infection report" },
      { name: "Outbreak Report", value: "outbreak report" },
      { name: "Mortality Report", value: "mortality report" },
      { name: "Recovery Report", value: "recovery report" },
    ],
  },
  {
    name: "Outreach Program Report",
    type: "outreach-program",
    reportTypes: [
      { name: "Event Report", value: "event report" },
      { name: "Participation Report", value: "participation report" },
      { name: "Feedback Report", value: "feedback report" },
      { name: "Impact Assessment Report", value: "impact assessment report" },
    ],
  },
];

export const MEDCONNECT_DASHBOARD_SUPER_ADMIN_TICKETS = [
  {
    status: "open",
    requestedBy: "Patrick Effiong",
    ticketID: "T001",
    subject: "Login Issue",
    description:
      "User unable to login with correct credentials. The system returns an error message stating 'invalid username or password'. The issue persists across different browsers and devices.",
    priority: "high",
    createdAt: "2024-07-01",
  },
  {
    status: "open",
    requestedBy: "Amaka Okafor",
    ticketID: "T002",
    subject: "System Crash",
    description:
      "The application crashes randomly while processing transactions. Users report losing unsaved data and experiencing system slowdowns before the crash.",
    priority: "high",
    createdAt: "2024-07-02",
  },
  {
    status: "closed",
    requestedBy: "Bola Adedeji",
    ticketID: "T003",
    subject: "Password Reset",
    description:
      "User requested a password reset but did not receive the reset email. Repeated attempts to request a new password reset email have failed.",
    priority: "medium",
    createdAt: "2024-07-03",
  },
  {
    status: "pending",
    requestedBy: "Chidi Nwosu",
    ticketID: "T004",
    subject: "Account Lockout",
    description:
      "User account is locked after multiple failed login attempts. User is unable to unlock the account using the provided unlock link.",
    priority: "high",
    createdAt: "2024-07-04",
  },
  {
    status: "open",
    requestedBy: "Damilola Johnson",
    ticketID: "T005",
    subject: "Data Sync Issue",
    description:
      "Data between the web application and mobile app is not syncing correctly. Users report missing or outdated information on one platform compared to the other.",
    priority: "high",
    createdAt: "2024-07-05",
  },
  {
    status: "in progress",
    requestedBy: "Esther Adeyemi",
    ticketID: "T006",
    subject: "UI Bug",
    description:
      "Certain UI elements are not displaying correctly on the dashboard page. Buttons and text are misaligned, and some images are not loading.",
    priority: "low",
    createdAt: "2024-07-06",
  },
  {
    status: "closed",
    requestedBy: "Femi Akinyemi",
    ticketID: "T007",
    subject: "Email Notification Issue",
    description:
      "Users are not receiving email notifications for updates and alerts. This issue affects multiple users and impacts important communication.",
    priority: "medium",
    createdAt: "2024-07-07",
  },
  {
    status: "open",
    requestedBy: "Grace Osei",
    ticketID: "T008",
    subject: "Payment Gateway Error",
    description:
      "Users are encountering errors during the payment process. Transactions are failing with a 'payment gateway error' message.",
    priority: "high",
    createdAt: "2024-07-08",
  },
  {
    status: "open",
    requestedBy: "Hassan Bello",
    ticketID: "T009",
    subject: "Slow Performance",
    description:
      "The application is experiencing slow performance during peak hours. Users report long loading times and delayed responses.",
    priority: "high",
    createdAt: "2024-07-09",
  },
  {
    status: "pending",
    requestedBy: "Idris Abubakar",
    ticketID: "T010",
    subject: "Feature Request",
    description:
      "User requested a new feature to allow batch processing of transactions. This feature would enhance productivity and user experience.",
    priority: "low",
    createdAt: "2024-07-10",
  },
  {
    status: "in progress",
    requestedBy: "Jane Mensah",
    ticketID: "T011",
    subject: "Database Error",
    description:
      "Users are experiencing 'database error' messages when trying to access certain records. This issue occurs intermittently and affects multiple users.",
    priority: "high",
    createdAt: "2024-07-11",
  },
  {
    status: "closed",
    requestedBy: "Kingsley Eze",
    ticketID: "T012",
    subject: "Security Vulnerability",
    description:
      "A potential security vulnerability was identified in the user authentication module. Immediate action is required to investigate and resolve the issue.",
    priority: "critical",
    createdAt: "2024-07-12",
  },
  {
    status: "open",
    requestedBy: "Linda Owusu",
    ticketID: "T013",
    subject: "Report Generation Issue",
    description:
      "Users are unable to generate reports. The system returns an error message 'report generation failed' and logs indicate a timeout error.",
    priority: "medium",
    createdAt: "2024-07-13",
  },
  {
    status: "pending",
    requestedBy: "Michael Yeboah",
    ticketID: "T014",
    subject: "API Integration Problem",
    description:
      "Issues with API integration are causing data discrepancies. Users report missing or incorrect data being displayed on the dashboard.",
    priority: "high",
    createdAt: "2024-07-14",
  },
  {
    status: "in progress",
    requestedBy: "Ngozi Obi",
    ticketID: "T015",
    subject: "Session Timeout",
    description:
      "Users are being logged out of the application prematurely due to session timeouts. This issue disrupts workflow and user experience.",
    priority: "high",
    createdAt: "2024-07-15",
  },
];
